# Generated by Django 6.0.6 on 2026-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_remove_tea_photo_tea_created_at_tea_origin_tea_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tea_photos/'),
        ),
    ]
