# Generated by Django 6.0.6 on 2026-06-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0003_tea_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
