# Generated by Django 6.0.6 on 2026-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0004_alter_tea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('Green', 'Green'), ('Black', 'Black'), ('Herbal', 'Herbal')], default='Green', max_length=50),
        ),
    ]
