name: Docker Build Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t tea-catalog-api .

      - name: Start Container
        run: |
          docker run -d \
            --name tea-api \
            -p 8000:8000 \
            -e SECRET_KEY=test_secret \
            -e DEBUG=False \
            -e ALLOWED_HOSTS=localhost \
            tea-catalog-api

      - name: Wait For Startup
        run: sleep 15

      - name: Health Check
        run: |
          curl --fail http://localhost:8000/api/health/

      - name: Show Container Logs
        if: always()
        run: |
          docker logs tea-catalog-api